# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

version: 2

linters:
  disable-all: true
  enable:
    - govet
    - unconvert
    - staticcheck
    - ineffassign
    - unparam

formatters:
  disable-all: true
  enable:
    - gofmt
    - goimports

run:
  concurrency: 2
  timeout: 1m
