# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

version: "2"

linters:
  enable:
    - govet
    - unconvert
    - staticcheck
    - ineffassign
    - unparam

run:
  concurrency: 2
  timeout: 1m
