url_docker_registry_dockerhub = "https://hub.docker.com/r/hashicorp/consul-ecs"
url_docker_registry_ecr = "https://gallery.ecr.aws/hashicorp/consul-ecs"
url_license           = "https://github.com/hashicorp/consul-ecs/blob/main/LICENSE"
url_project_website = "https://www.consul.io/docs/ecs"
url_source_repository = "https://github.com/hashicorp/consul-ecs"
